### ISSUE TITLE
Big white space at top of main page. 

### ISSUE THREAD

**Issue by kylec32** [kylec32/recipe-holder#1]
On the main screen there is a large whitespace at the top of the screen. Should get rid of that. 

![screen shot 2016-10-02 at 11 52 20 am](https://cloud.githubusercontent.com/assets/160703/19022475/bd47edf6-8896-11e6-8562-c404221e166b.png)

**Comment by zakaye** [comment]
I'm having a look :>

**Comment by flyingfisch** [comment]
@zakaye are you still working on this or is it ok if I give it a shot?

**Comment by jmerle** [comment]
Oh, didn't see flyingfisch's comment nor kylec32's reference (whatever that may mean) in time. I'm sorry if I just took someone's issue (I assumed kylec32 stopped working on it but didn't see the reference, somehow).

**Comment by zakaye** [comment]
I apologize for not updating here but its already fixed, i just added a new css rule set for the page header for activityPicker.html and made the top margin -80px so it  no longer shows. You could see if there's a better way if you want to.
